### PR TITLE
Add portuguese translation config

### LINKED ISSUE #110: Add Portuguese language support
#### Describe the desired behavior
Add the Portuguese translation option onto the login screen

#### Describe the current behavior
It is not there yet. 

#### Is this request related to a current issue?
No

#### Additional Context
PT was recently added to the React Auth Workflow, but not for the RN Auth Workflow.

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #110 & BLUI-2962 .

#### Changes proposed in this Pull Request:
- Add support for Portuguese

#### Screenshots:
Simulator Screen Shot - iPhone 12 - 2022-07-29 at 14 57 25

#### To Test:
- replace line 33 in the example apps `App.tsx` with `void i18n.changeLanguage('pt');`
- `yarn start:example`
- observe text is all translated to Portuguese

### CODE REVIEW

**Comment by jeffvg** [comment]
look like these tag are back on forgot password screen, thought we fixed this before or maybe different lang?

image

**Comment by jeffvg** [comment]
verify email on reg screen formatting

image

**Comment by jeffvg** [comment]
The contact us screen missing space between parasomething@email.com

image

**Comment by jeffvg** [comment]
Change password screen title not translated also padding seems off but maybe its my system

image

**Comment by daileytj** [comment]
@jeffvg  These are all issues in the react-auth-shared translations files. I'll update to use the latest version of auth shared, which may resolve some of these, but these issues will need to be addressed there.

**Comment by jeffvg** [comment]
did you want to catch the extra fields on self reg, country & currency?

image

**Comment by daileytj** [comment]
> did you want to catch the extra fields on self reg, country & currency?
> 
> image

no... these are custom fields and they aren't being translated for any language

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
