### PR TITLE
Feature/allow direct inclusion from yarn

### PR DESCRIPTION
**Pull request by BrettThePark**
#### Changes proposed in this Pull Request:
- These changes allow master, branches, or forks to be used via Yarn > 2.1 rather than just the NPM

### CODE REVIEW

**Comment by BrettThePark** [comment]
There is some sort of issue with jest and a newer version of the babel runtime that is causing the test not to run. I don't have any spare cycles to determine the conflict causing the test infrastructure to fail.

**Comment by daileytj** [comment]
@BrettThePark I can clean up the test issues if we're going to merge this in, but what exactly are you trying to add here? Could you clarify a bit because I'm not sure what problem you are trying to solve by what I see here. I'm going to point this PR at `dev` as well. Please be sure to open your PR's to merge with `dev` in the future.

**Comment by BrettThePark** [comment]
Sometimes we need to use a branch or fork of this library while waiting for the PR process. Since the login-workflow is in a subfolder and requires packing we are not able to add a fork or branch explicitly via Yarn through the package.json file. It requires us to wait for a proper NPM release before using it. This PR sets up the repo with a workspace that allows us to directly add the git link (for the branch or fork) into our project so we can utilize intermediate releases as needed to prevent project development blocking.

**Comment by daileytj** [comment]
@BrettThePark I've been looking into a solution for this with no success yet. I'll keep working on it, but if you want to take some time to test locally as well that would be great. The same error arises when you run `yarn test` from the login-workflow folder. We also discussed restructuring this repo in the future to bring the login workflow to the top level, but we have yet to determine a timeline for this.

**Pull request merged**
