### PR TITLE
BLUI-2778 add username login functionality

### LINKED ISSUE #112: Add support for logging in with username instead of email address
#### Describe the desired behavior
Users should be able to specify that they want to use username/password credentials instead of email/password.

#### Describe the current behavior
Only email/password is supported.

#### Is this request related to a current issue?
We made this possible in a hacky way on React already, but we have another story to improve that implementation.

#### Additional Context

- Do we need to handle validation?
- What do we show for labels?
- Custom email regex validators too?

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #112 /BLUI-2778.

#### Changes proposed in this Pull Request:
- add username login functionality

#### Screenshots:
Simulator Screen Shot - iPhone 12 - 2022-08-04 at 14 09 59

#### To Test:
- Clone RN workflows repo
- Be sure you are using the following branch for the auth-shared submodule `feature/blui-2778-add-username-regex-and-translations`
- Uncomment line 83 of the example `App.tsx` file and run `yarn start:example`
- Observe username field and make sure you can log in using it
- The default is 'email', so be sure to test the explicit case where you set it to email and the case where you provide no value for the `loginType` prop on the `AuthUIContextProvider`

### CODE REVIEW

**Comment by ektasawant** [comment]
Not related to this story but if we are using loginType: username. Then in forgot password page will it ask email / username?

**Comment by ektasawant** [comment]
Able to login with username, remember Me works fine 👍 
Screenshot 2022-08-05 at 2 27 02 PM

Default logintype works
Screenshot 2022-08-05 at 2 30 47 PM

loginType with `email` works
Screenshot 2022-08-05 at 2 30 36 PM

**Review by ektasawant — APPROVED** [review]

**Comment by jeffvg** [comment]
should we have requirements around username for anything? When running with username login we can use anything?

image

**Comment by daileytj** [comment]
> Not related to this story but if we are using loginType: username. Then in forgot password page will it ask email / username?

This is a good catch. This should probably be done in react as well.

**Comment by daileytj** [comment]
> should we have requirements around username for anything? When running with username login we can use anything?
> 
> image

This is a good call. @emclaug2 @huayunh Any thoughts on appropriate checks here? No whitespace? Character limit? @joebochill Does Brightlayer Cloud already have defined requirements around this?

**Comment by emclaug2** [comment]
> > should we have requirements around username for anything? When running with username login we can use anything?
> > image
> 
> This is a good call. @emclaug2 @huayunh Any thoughts on appropriate checks here? No whitespace? Character limit? @joebochill Does Brightlayer Cloud already have defined requirements around this?

I'd keep it simple, no whitespace sounds good to me.

**Comment by joebochill** [comment]
BLC does not support usernames , they are email only. This feature is for teams using alternative back ends or, in most cases, built-in credentials on a device. No white space sounds fine for now. In the future for react and RN we could consider exposing something like a usernamePattern prop where users can supply their own custom regex.

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
