### PR TITLE
v4.2.0 Cleanup - Center dialog, errorMessage, and AccountDetails for selfRegistration

### PR DESCRIPTION
**Pull request by daileytj**
#### Changes proposed in this Pull Request:
- Center dialog, errorMessage, and AccountDetails for selfRegistration
- Ensure the keyboard next button works

#### To Test:
- Test this on as many devices as possible...
- Ensure that everything is looking nice on phone and tablet in regards to the issues in milestone 4.2.0

### CODE REVIEW

**Comment by daileytj** [comment]
Some screenshots of how things look right now...

Screen Shot 2022-09-08 at 1 47 46 PM
Screen Shot 2022-09-08 at 1 47 55 PM

https://user-images.githubusercontent.com/13989985/189193871-0702c4dd-f869-4ff5-8cc4-44034190dbe4.mov

Screen Shot 2022-09-08 at 1 52 19 PM
Screen Shot 2022-09-08 at 1 52 37 PM
Screen Shot 2022-09-08 at 1 52 47 PM

https://user-images.githubusercontent.com/13989985/189193896-b5c7e927-eeb3-4162-94b6-979f93146f74.mov


https://user-images.githubusercontent.com/13989985/189193902-56710d65-9e4b-49b7-aef8-08d96b92a0a1.mov

Screen Shot 2022-09-08 at 1 47 36 PM

**Comment by jeffvg** [comment]
I'll write up a new issue for this since its in dev but on Android only when regex validation checker completes on email address or password fields the keyboard closes on emulator. That being said the Android emulator allows the virtual keyboard to be open and you can use the hardware keyboard at the same time unlike iOS simulators. It's been a while and not sure if we actually wanted this behavior or not. For the email validation anything beyond the ".co" the checker completes when we should allow the entire email to be entered... someone@here.com


https://user-images.githubusercontent.com/37150565/189369619-d7495193-6ba5-4139-9629-05fcda897607.mov


https://user-images.githubusercontent.com/37150565/189369648-3ad81dba-69de-4851-853b-4302ab5126d3.mov

**Comment by daileytj** [comment]
@jeffvg we may want to test that android keyboard issue on master because the dev branch code isn't what is out in the wild right now. I'll check that now.

**Comment by jeffvg** [comment]
> @jeffvg we may want to test that android keyboard issue on master because the dev branch code isn't what is out in the wild right now. I'll check that now.

keyboard remains open running master

image

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
