### PR TITLE
Fill eula and email on deeplink and wrap pages in views

### PR DESCRIPTION
**Pull request by BrettThePark**
#### Changes proposed in this Pull Request:
- When coming from a deep link to self-registration, EULA should be already accepted and the email should be entered in case the user goes back.
- Wrap PagerView views in an empty view (no flex) to avoid over-optimization (resulting in "blank" pages).

React-Native-Pager-View might have to be changed to `https://github.com/Shiverware/react-native-pager-view.git` in order to fix some of the issues in the current pager release.

### CODE REVIEW

**Comment by emclaug2** [comment]
Thanks for the PR, Brett; I've updated the base from master to dev & will take a look at this shortly.

**Comment by emclaug2** [comment]
@joebochill @BrettThePark Is the intension here to skip the EULA page whenever there is a verification code provided?  The code looks great, I just want to verify this is the intended workflow behavior.  

If a registration link is provided, the user is already assumed to accept the EULA.

**Comment by BrettThePark** [comment]
Skipping the EULA is part of the intent. When a user is creating an account, they are emailed the code. In order to have been emailed the code, they will have been forced to accept the EULA. When the user opens their email, they can tap on the link to open the app and continue registration. There are two cases here, one is where the app is already open and waiting for the verification code. The other is that the app has been terminated or is on some other screen. In that case (as long as some other user isn't already authenticated), the EULA gets marked as accepted, the email they had used for registration is filled in (it needs to have been provided in the link) and the verification code gets entered/verified.

**Comment by emclaug2** [comment]
Great explanation, thanks Brett! The changes look good to me.

**Comment by emclaug2** [comment]
I'll make a follow-up PR to adjust the changelog.

**Pull request merged**
