### PR TITLE
Added safe area view to change password screen

### LINKED ISSUE #207: Change password screen, the bottom button footer should not be floating
#### What is the expected behavior?
It should be pinned to the bottom, right above that home slider. See [docit](https://brightlayer-ui-dev.github.io/patterns/buttons#responsive) for description.

#### What are the steps to reproduce?
1. Go to showcase
2. log in, then change password
3. observe that the "cancel" and "update" button is floating, instead of pinned to the bottom

#### Screenshots / Screen recording

image

#### Suggested fix

Joe said 
```
bottom: 0
```
But I suspect it might need more than that for the sake of safe area

#### Anything else to add?
Discovered during the code demo

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #207 

#### Changes proposed in this Pull Request:
- Added bottom style for change password screen

#### Screenshots:
Screenshot 2022-12-22 at 11 41 31 PM

#### To Test:
- yarn start:example

### CODE REVIEW

**Comment by huayunh** [comment]
Just eyeballing from this screenshot, the bottom is too narrow. Either a paddingBottom:16 is missing somewhere, or the safe area view is not being set up properly.

image

**Comment by bkarambe** [comment]
@huayunh Please review.

**Comment by bkarambe** [comment]
@joebochill @huayunh Please review.

**Comment by joebochill** [comment]
There's an interesting new behavior with the new code location of the changepassword dialog. 

https://user-images.githubusercontent.com/29152776/209340687-c23a13f3-32a0-4f2e-9a13-f12f4a36caca.mov

I think this is fine though...the positioning of the buttons looks much better!

**Comment by daileytj** [comment]
@joebochill are you cool with that overscroll you commented on last week?

**Comment by joebochill** [comment]
> @joebochill are you cool with that overscroll you commented on last week?

Yes. Let’s long a big for it so we don’t forget about it, but we don’t have to fix it for this.

**Review by daileytj — APPROVED** [review]

**Pull request merged**
