### PR TITLE
BLUI-2967 custom success screen styles

### LINKED ISSUE #55: Example project custom success screen style update
#### Describe the desired behavior
The continue button on the custom success screens should be pinned to the bottom.

#### Describe the current behavior
The continue button is not at the bottom.
Simulator Screen Shot - iPhone 12 - 2021-04-23 at 09 50 38

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #55 & BLUI-2967.

#### Changes proposed in this Pull Request:
- Update custom success screen styles

#### Screenshots:
Simulator Screen Shot - iPhone 12 - 2022-08-17 at 15 56 05

#### To Test:
- Run the example project and walk through either of the registration workflows. The final screen will be the custom success screen with updated styles. Ensure that it matches the screenshot provided.

### CODE REVIEW

**Comment by huayunh** [comment]
On my end, `yarn start:example` yields different button y-positions, depending on which workflow is selected:

image

**Comment by daileytj** [comment]
@huayunh this should be good to go now

**Comment by huayunh** [comment]
Now I see this from both the "register now" and "test invite register" routes, but surprisingly not from the "test self register" route:

image

```
 ERROR  Warning: React has detected a change in the order of Hooks called by SelfRegistrationPager. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks
```

**Comment by huayunh** [comment]
Also, depending on how perfectionist you are,

image

(these were correct before, but it looks like it got changed in the last commit)

**Comment by huayunh** [comment]
The Y position looks good otherwise

**Review by huayunh — APPROVED** [review]
Didn't run the simulator after since your second to last commit but changes look good

**Pull request merged**
