### PR TITLE
Verification code button style update

### LINKED ISSUE #157: Can we move Verification code button to diffrent spot on Verify email page
@joebochill  just an suggestion , can we move verification code button to different spot as when we type verification code,  keyboard gets enable due to that next button looks hidden . then we press reset verification email button . 

Simulator Screen Shot - iPhone 13 - 2022-06-17 at 15 59 50

### PR DESCRIPTION
**Pull request by daileytj**
BLUI-3269
Fixes #157 

#### Changes proposed in this Pull Request:
- Verification code button style update

#### To Test:
- Clone react-native-workflow project
- Initialize react-auth-shared submodule using branch `feature/3269-add-verification-code-prompt-translation-text`
- `yarn start:example`
- Go to self registration workflow (click debug button, then click self-registration button)
- Navigate to the third screen in the workflow to visit the verification code page
- Observe the updated view

### CODE REVIEW

**Comment by daileytj** [comment]
https://github.com/brightlayer-ui/react-native-workflows/issues/157#issuecomment-1172617553 will need addressed before I switch this to an active pull request

**Comment by daileytj** [comment]
Running into testing issues and I can't seem to track down what change caused this. https://github.com/ptelad/react-native-iphone-x-helper/issues/38

**Comment by daileytj** [comment]
Made a PR into the react-native-iphone-helper repo: https://github.com/ptelad/react-native-iphone-x-helper/pull/41

this fixes the first issue I ran into, but now I'm getting a new issue shown in the screenshot below.
I've already tried to clear the jest cache as well. I'm thinking there is some bigger underlying issue I can't quite figure out.

Screen Shot 2022-07-06 at 3 09 33 PM

**Comment by ektasawant** [comment]
Screenshot 2022-07-07 at 12 27 05 PM

**Pull request closed without merging**
