### PR TITLE
BLUI-2966 Fix keyboard next button with refs

### LINKED ISSUE #73: Keyboard next button does not work
#### Describe the bug
Since the latest custom pages were added, the keyboard next button does not move out of last name field to the country field. Once you click in to country field and press the keyboard next button it works and goes to currency field. The last custom page for job info does not display the done keyboard button.  
#### What is the expected behavior?
Keyboard next button to move to next field and to have the done button available for the last page of job info
#### What are the steps to reproduce?
1. Run through setup new account using iPad, iPhone or Android
2. Use next keyboard button from first name to last name then to country. The keyboard closes.
3. Job info page should change to use the done button once in the last field

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #73 & BLUI-2966.

#### Changes proposed in this Pull Request:
- Fix keyboard next button for navigating between default account details and custom account details

#### To Test:
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git -b feature/blui-2966-fix-keyboard-next-button-with-refs`
- `cd react-native-workflows/login-workflow`
- `yarn initialize`
- `cd shared-auth && git checkout feature/blui-2966-fix-keyboard-next-button-with-refs`
- `cd .. && yarn start:example`
- check both "Invite Register" and "Self Register" flows to ensure that you can navigate between pages and form fields using the native keyboard next buttons.

Note: There's a weird bounce that happens when moving to the 3rd and 4th input fields. I've checked this and it's an issue across the board if the form extends below the keyboard. If we want this fixed specifically it will need addressed in another story

Disclaimer: I need to update some docs around this, but want to make sure this method works first before documenting it.

### CODE REVIEW

**Comment by jeffvg** [comment]
on a fresh clone, the keyboard doesn't open when selecting any input fields. I'm also throwing this error in the metro terminal...

image

**Comment by jeffvg** [comment]
on iOS the next button seems to be working fine with no issues.  Unable to test out android at the moment due to the keyboard dismissed on every input field select. Can you merge in latest from release/4.2.0 to get the android manifest update we had earlier last week?

**Comment by jeffvg** [comment]
I added the android manifest update to get running. Android has that glitch or bounce like iOS but android has slightly different behavior...notice the bounce and keyboard closes..


https://user-images.githubusercontent.com/37150565/187274671-2461af2f-c8b2-440a-a802-fdd363207ee0.mov

**Comment by daileytj** [comment]
@jeffvg Interesting... @huayunh @joebochill @emclaug2 @bkarambe @ektasawant Does anyone have a physical android device they can test this on?

**Comment by jeffvg** [comment]
> @jeffvg Interesting... @huayunh @joebochill @emclaug2 @bkarambe @ektasawant Does anyone have a physical android device they can test this on?

I have one here, it's just going to take a few to get charged up and running the app

**Comment by daileytj** [comment]
> > @jeffvg Interesting... @huayunh @joebochill @emclaug2 @bkarambe @ektasawant Does anyone have a physical android device they can test this on?
> 
> I have one here, it's just going to take a few to get charged up and running the app

Awesome... sounds good. Thanks for going all in on these RN PR's.

**Comment by jeffvg** [comment]
> > > @jeffvg Interesting... @huayunh @joebochill @emclaug2 @bkarambe @ektasawant Does anyone have a physical android device they can test this on?
> > 
> > 
> > I have one here, it's just going to take a few to get charged up and running the app
> 
> Awesome... sounds good. Thanks for going all in on these RN PR's.

thought I had a cable to use for android but no luck...only way to get this on android for me would be to generate a metro QR code to scan with metro client on my phone. Any idea how to do that?

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
